### ISSUE TITLE
First Issue

### ISSUE THREAD

**Issue by rwadada** [exchange-lab/wiki#1]
What do you want to develop?  
 -

**Comment by dKATO0424** [comment]
Hi rwadada. Nice to meet you.
I want OSS that can be customized and can perform quality analysis without calculation software.
I think about Inception Deck from now on.

**Comment by rwadada** [comment]
test

**Comment by rwadada** [comment]
test2

**Comment by rwadada** [comment]
I want to develop like this  
[sample page](https://xd.adobe.com/view/7a583f31-d6d6-4720-7070-a79939b7f85f-0c69/?fullscreen)  
It can use in the same way as Excel and can also write in MD. And it makes version control easy by outputting as HTML.

**Comment by dKATO0424** [comment]
Great! 
An interface similar to Excel can be used by users who can only use Excel. That will make us happy.
